#cloud-config
ssh_pwauth: no

users:
  - name: user
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh-authorized-keys:
      - "${SSH_KEY}"

write_files:
  - path: /root/vm_prep.sh
    permissions: "0750"
    content: |
      #!/bin/bash
      set -eux

      apt-get update
      apt-get install -y ca-certificates curl gnupg lsb-release

      mkdir -p /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor | tee /etc/apt/keyrings/docker.gpg > /dev/null

      printf "%s\n" \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        | tee /etc/apt/sources.list.d/docker.list > /dev/null

      apt-get update
      apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

      systemctl enable --now docker
      usermod -aG docker user

runcmd:
  - sleep 120
  - sudo -i
  - /root/vm_prep.sh